name: Check if this workload reacts to changes on release/* branches
on:
  push:
    branches:
      - 'release/**'
jobs:
    create_jenkins_branch:
      name: Creates jenkins/release/* branch if it does not exist
      runs-on: ubuntu-latest
      steps:
        - name: Fetch full history
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
