name: Test
on:
  milestone:
    types: [closed]
jobs:
    create_stable_branch:
        name: Builds stable branch when closing a milestone
        runs-on: ubuntu-latest
        steps:
            - name: Fetch full history
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Builds stable branch when closing a milestone
              run: |
                git checkout release/${{ github.event.milestone.title }}
                git checkout -b stable/${{ github.event.milestone.title }}
                git push origin stable/${{ github.event.milestone.title }}
